Couleur pour 15-15
ansforge/SAMU-Hub-Modeles pull request #10
Opened 2023-12-18 13:48 UTC by saveliy-sviridov

Ajout d'un mécanisme permettant de distinguer les nomenclatures spécifiques au 15-15

2023-12-18 17:33 UTC, romainfd reviewed
Super ! Le cas des propriétés à gérer mais on est pas mal je pense !!
Si possible, hésite pas à mettre quelques screens ça permet de bien voir ce que ça donne :)

2023-12-18 17:33 UTC, romainfd commented on csv_parser/uml_generator.py
> +            buffer_description_node[id_parent] = buffer_description_node[id_parent] + "<BR/>" + "is_health_only: True"
Plus élégant/light d'ajouter juste une icône ? -> ⚕️ou 🩺 ou 🏥 ou ... https://emojidb.org/health-emojis ?
Ou on peut utiliser des '*' même si ça fait un peu penser à "obligatoire" plutôt.

2023-12-18 17:33 UTC, romainfd commented on csv_parser/uml_generator.py
> +        dot.node(id_in, str_node, fillcolor="lightgreen", style="filled")
Comme ce sont des données plus sensibles, peut-être les mettre plutôt en rouge non ?

2023-12-18 17:33 UTC, romainfd commented on csv_parser/csv_parser.py
> +            'x-health-only': child['is_health_only'],
En le mettant là, tu vas gérer les objets purement 15-15 !
Mais les objets partagés avec une propriété en plus qui serait que 15-15 ne seront pas gérés sans ajout dans add_field_child_property non ?
ex : reqtype dans caller notamment

2023-12-20 08:51 UTC, saveliy-sviridov commented on csv_parser/uml_generator.py
> +            buffer_description_node[id_parent] = buffer_description_node[id_parent] + "<BR/>" + "is_health_only: True"
J'ai pas l'impression que les icones s'affichent proprement; sinon est-ce que juste **15-15** après la propriété/type te parait approprié?
![image](https://github.com/ansforge/SAMU-Hub-Modeles/assets/105354733/be38345d-01ae-4b0e-944a-b3f4d9fe4ee1)

2023-12-21 18:10 UTC, romainfd requested changes
Plus propre déjà !
Si possible, améliorer le rendu visuel

2023-12-21 18:10 UTC, romainfd commented on csv_parser/uml_generator.py
> +        dot.node(id_in, str_node, fillcolor="firebrick1", style="filled")
Ca serait possible de faire un rouge beaucoup plus pastel / léger ?
Et ne pas dépasser de la boite ?

2023-12-21 18:10 UTC, romainfd commented on csv_parser/uml_generator.py
> +        dot.node(id_in, str_node, fillcolor="firebrick1", style="filled")
Là, il est rouge dès qu'il a un champ 15-15 alors que ce n'est pas vraiment ce qu'on voudrait (notamment pour createCase qui devient tout rouge)
<img width="192" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/4306c765-c142-43ed-8feb-baac492d258a">

Est-ce que ça serait possible :

- lorsqu'un objet est ajouté dans le 15-15 mettre en rouge son header (et si plus simple possible d'écrire en rouge aussi les champs même si pas idéal) (ex : que le chapeau 'patients' en haut aurait un fond rouge pas toute la boite)
<img width="130" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/5f522311-2deb-4b6f-8265-1b975a754db0">

- lorsqu'un objet existait déjà dans le 15-18, écrire en rouge que les champs qui sont 15-15 : d'écrire en rouge (ex : createCase -> écrire owner en rouge seulement)
<img width="129" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/57acdcf6-12af-42f4-a4d3-395eca272508">

- pour éviter les différences, est-ce que quand l'objet est 15-15, pas besoin de mettre 15-15 sur ses attributs. Notamment parce que certains objets purs 15-15 qui réutilisent des types définis en 15-18, se retrouve sans le 15-15 sur leur champs alors qu'ils sont bien entièrement 15-15
<img width="104" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/57c4f115-e357-4b2d-a6f5-87125c2a3ccf">

2023-12-21 18:15 UTC, romainfd commented on csv_parser/uml_generator.py
> +                print("Adding node " + id_child + " to " + id_parent + "child content: "+ str(buffer_description_node[id_child]))
L'enlever non ? C'est bruyant dans les logs pour un intérêt limité
Tu as réussi à mettre en place visual studio code et un débuguer ?

2023-12-22 18:22 UTC, merged