Argument d'entrée pour filtrer sur 15-NexSIS
ansforge/SAMU-Hub-Modeles pull request #11
Opened 2023-12-18 16:42 UTC by saveliy-sviridov

Ajout d'un argument d'entrée --filtre, permettant de filtrer uniquement sur les nomenclatures de 15-NexSIS et créer des fichiers de sortie suffixés par '-CISU'

2023-12-18 17:43 UTC, romainfd reviewed
Bon début ! L'objectif est bien d'obtenir un dossier RC-EDA et un dossier RC-EDA-CISU on est d'accord ? Ou on fait un dossier out/CISU/ dans lequel on a les dossier RC-EDA, ... qui seront filtrés en version CISU ?

2023-12-18 17:43 UTC, romainfd commented on csv_parser/csv_parser.py
Plutôt que d'avoir des if partout, tu peux avoir un bloc de ce style au début :
```python 
appendCisuIfNeeded = '-CISU' if args.filter else ''
```
Et après, tu as juste à rajouter ça dans les noms de fichiers ! EX : `'out/{args.sheet}/{args.sheet}{appendCisuIfNeeded}.schema.json'`

2023-12-18 17:43 UTC, romainfd commented on csv_parser/out/EMSI/EMSI.schema.json
Il y a bcp de changement dans ce fichier, je suis pas sûr que ce soit normal !

2023-12-18 17:43 UTC, romainfd commented on csv_parser/out/EMSI/example.json
> +        "RESOURCE": [
idem (mais logique ils vont ensemble) et ça va être le cas pour tous les autres out/EMSI

2023-12-18 17:43 UTC, romainfd commented on csv_parser/out/EMSI/EMSI.schema.json
Ca venait de colonne 15-15 et 15-NexSIS mal remplie pour l'EMSI
C'est une norme internationale donc on prend tous les champs dans les 2 cas, pas le choix !
-> j'ai corrigé dans l'excel, tu peux le copier et relancer

2023-12-18 17:43 UTC, romainfd commented on csv_parser/uml_generator.py
> +        dot.render(os.path.join("out", model, "uml_schema_CISU" if filter else "uml_schema"))
En voyant ça, je me rend compte qu'il faudrait qu'on mette aussi le nom de modèle dans tous les outputs non ? La dans EMSI/ ou RC-EDA/ plein de fichiers ont le même nom ce qui ne facilitent pas leur utilisation. Ou on considère qu'une fois dans le bon dossier, on sait déjà de quoi on parle ? Tu en penses quoi ?

2023-12-20 09:44 UTC, saveliy-sviridov commented on csv_parser/uml_generator.py
> +        dot.render(os.path.join("out", model, "uml_schema_CISU" if filter else "uml_schema"))
Je pense que c'est une bonne idée, même si c'est un peu redondant d'avoir des chemins de type "RC-EDA/RC-EDA-uml_schema" ca peut rendre les fichiers plus pratiques à utiliser.

2023-12-21 17:44 UTC, romainfd approved these changes
Ca me semble OK tout ça !

2023-12-21 17:46 UTC, romainfd requested changes
Possible de résoudre les conflits ? Pas de soucis pour écraser les fichiers générés mais les autres (notamment les .py), il faut régler les conflits proprement

2023-12-22 18:16 UTC, romainfd approved these changes
LGTM !

2023-12-22 18:16 UTC, merged