Fix/Message lors d'un erreur dans l'en-tete
ansforge/SAMU-Hub-Modeles pull request #28
Opened 2024-01-17 14:09 UTC by saveliy-sviridov

Ajout d'un message d'erreur si l'erreur est détecté dans l'en-tête (DistributionElement)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206347982103249

2024-01-17 15:43 UTC, saveliy-sviridov commented on src/main/java/com/hubsante/model/Validator.java
> +                    return errorMsg.getMessage().substring(errorMsg.getMessage().indexOf("message") + 8);
Il existe potentiellement un problème de distinction entre RC-EDA et RS-EDA, une erreur concernant la manque du champ "createCase.owner" est relevé en même temps que l'erreur de l'en-tête

2024-01-17 16:36 UTC, romainfd requested changes
Excellent ! Petite modif sur le fichier de test + la logique de contrôle sur le RC-DE

2024-01-17 16:36 UTC, romainfd commented on src/main/resources/sample/failing/RC-EDA/invalid-RC-DE-header-error.json
> +              "URI": "hubex:fr.health.samuA"
Pour les messages de test, pour éviter de devoir maintenir de gros JSON, on utilise customContent dès que possible. Comme il a pas de RC-DE, utilise plutôt un RC-REF qui est petit également non ?

2024-01-17 16:36 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +                if (errorMsg.getMessage().contains(attribute.getName())) {
Est-ce que c'est pas un peu large comme check ? Si on ajoute un field `message` au RC-DE ça va matcher tout le temps alors que ce qu'on veut matcher c'est embeddedJsonContent.message.attribute plutôt non ?

2024-01-17 16:36 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +            // In the latter case, we return the error message (without the $. at the start), and to verify
```suggestion
            // In the latter case, we return the error message (starting after the ....message.), and to verify
```

2024-01-17 16:36 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +            Field[] attributes = DistributionElement.class.getDeclaredFields();
Excellent !!!!

2024-01-19 16:32 UTC, saveliy-sviridov commented on src/main/java/com/hubsante/model/Validator.java
> +            boolean infoError = false;
Les flags commencent a s'empiler un peu, mais je vois pas comment faire autrement vu qu'on aura forcement les erreurs de validation de RC-DE dans les RS-INFO

2024-01-19 17:04 UTC, romainfd requested changes
Pour en rediscuter ! Notamment sur la logique !

2024-01-19 17:04 UTC, romainfd commented on src/main/resources/sample/failing/RC-EDA/invalid-RC-DE-header-error.json
> +              "URI": "hubex:fr.health.samuA"
A migrer vers un RC-REF si possible

2024-01-19 17:04 UTC, romainfd commented on src/main/resources/json-schema/EDXL-DE-full.schema.json
> +              "additionalProperties": false
Il faudrait voir avec Benjamin (et demander ça review sur ça d'ailleurs aussi, il est bcp plus familier que moi sur la partie Modèle) si c'est OK ou si justement c'est le niveau 'root' qui fait casser des choses si on met l'additionalProperties

2024-02-13 14:46 UTC, romainfd requested changes
Vu le nombre de tests, j'ai envie de penser que ça fait ce qu'on veut mais j'en suis pas complètement sûr... Est-ce que tu pourrais générer pour tous les messages failing, les messages "bruts" d'erreur de la librairie de validation ?
Comme ça on pourrait voir plus facilement de quoi on part et vers quoi on veut aller

2024-02-13 14:46 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +        return result;
L'enveloppe contient des objets (ex : descriptor.explicitAddress), est-ce que ces derniers seront bien gérés ici ? plutôt jouer sur la longueur du chemin ?

2024-02-13 14:46 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +        // is in RS-INFO (important to know because we won't keep RS-DE errors if the message is RS-INFO.)
RC-DE ?

2024-02-13 14:46 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
> +                    if (substring.contains(attribute.getName())) {
Est-ce que ça ne détecterait pas à tort un champ 'sender' en erreur dans un RC-EDA (n'existe pas mais pour l'exemple) en pensant que c'est celui du RC-DE ? A nouveau, je pense qu'il faut une logique de profondeur

2024-02-13 14:46 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
Je trouve la logique encore un peu compliquée... Je me demande si ça pourrait pas être simplifié en s'appuyant sur notre brainstorming ou si je rate quelque chose ? J'ai l'impression qu'on peut facilement raté des corner cases et je trouve pas le parsing très "rigoureux", ça m'inquiète un peu. Est-ce qu'on devrait envoyé un "rawErrorMessage" en plus ou on met le dump non parsé des erreurs ? Ou au moins le logger pour que si on investigue une erreur qui a été supprimé par erreur par cette logique, on ne tourne pas en rond pendant 200 ans parce qu'on la verra pas.
Bref, pas ultra serein sur le système...
<img width="546" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/af78e344-274d-458f-a5a9-d60b93bf17ea">

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-completely-missing-RC-DE.json
C'est pas un RC-REF mais un RS-EDA => changer le contenu vers un RC-REF pour que ça soit court

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-error-in-RC-DE.json
> +{
Dans les messages d'erreur, c'est pas mal d'ajouter là où est l'erreur
Utiliser le recipient.name par exemple ou un champs pas trop loin de l'erreur (c'est recipentS l'erreur ici non ?)

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-error-in-content.json
> +              "distributionIDS": "samuB_2607723d-507d-4cbf-bf74-12345f7064cd"
Mettre "_ERROR" pour que ce soit plus visible, comme dans les autres erreurs

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-error-in-RC-DE.json
> +{
Ou juste un mesageID_ERROR comme pour les autres ?

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-too-many-schemas-and-errors-in-content.json
> +            "emsi": {
Mettre un custom Content plutôt ? ou RS-INFO ? Bref un truc plus court

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-too-many-schemas-and-errors-in-content.json
> +              "incorrectProp": "samuB_2607723d-507d-4cbf-bf74-12345f7064cd"
garder la logique avec _ERROR

2024-02-13 14:46 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-too-many-schemas.json
> +            "emsi": {
Idem : enlever le createCase et emsi et mettre customContent et/ou RS-INFO

2024-02-13 14:46 UTC, romainfd commented on src/test/java/com/hubsante/model/EdxlHandlerTest.java
> +        String json = getInvalidMessage("EDXL-DE/unknown-property-at-root.json");
Ca devrait fail ça avec les dernières modifs non ?

2024-02-13 14:46 UTC, romainfd commented on src/test/java/com/hubsante/model/ValidatorTest.java
> +    }
A priori, on devrait pouvoir savoir qu'on est dans ce cas là et renvoyer une meilleure erreur !
Et le fichier utilisé me parait pas étrange "EDXL-DE/unknown-property-at-root.json" par rapport au nom "RC-DE validation..."

2024-02-13 14:46 UTC, romainfd commented on src/test/java/com/hubsante/model/ValidatorTest.java
> +            checkErrorMessagePresence(errors, MISSING, "recipient: ");
Je me demande si l'objectif, surtout quand on a des petits tests, ne serait pas de checker exactement que le message correspond à ce qu'on attend.
Parce que là, c'est dur de savoir avec les tests si on avait d'autres lignes par exemple alors qu'on ne les voudrait pas. 
=> sans aucun filtering, on passerait ces tests alors que ça ne correspond pas à ce qu'on veut

2024-02-13 14:50 UTC, romainfd commented on src/test/java/com/hubsante/model/EdxlHandlerTest.java
> +        String json = getInvalidMessage("EDXL-DE/unknown-property-at-root.json");
Effectivement, c'est le cas dans la PR #29

2024-02-13 14:55 UTC, romainfd commented
J'ai mergé la PR #29 
Possible de remettre properties au dessus de definitions dans les schémas EDXL ?

2024-02-15 16:29 UTC, romainfd requested changes
Petite incompréhension sur le renommage _ERROR
Et je trouve la logique de validation pas encore assez fluide / refactorée mais si tu le sens, ça me suffit

2024-02-15 16:29 UTC, romainfd commented on src/main/resources/sample/failing/RC-REF/RC-REF-error-in-envelope-and-RC-DE.json
> +  "_errordistributionID": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
Je pensais plus à `distributionID_ERROR` pour faciliter la visibilité
Le `_error` devant est un peu étrange. Possible de basculer vers `ERROR_` si on reste devant ?

2024-02-15 16:29 UTC, romainfd commented on src/main/java/com/hubsante/model/Validator.java
>                  if (error != null) {
Je trouve pas que `validateJSON` soit très claire encore...
Je pense qu'il faut faire un travail de reprise, simplification, refactoring de la logique.
En plus, c'est assez sensible comme composant parce que ça va renvoyer automatiquement des messages d'erreurs aux éditeurs donc si on leur renvoie des infos fausses à cause de nos manips, ça va vraiment les perdre et donner une très mauvaise image
Comme en plus, on a 0 monitoring sur tout ça pour le moment en plus, il faut vraiment qu'on fasse gaffe et je trouve que le code actuel n'est pas très clair ni auditable / modifiable facilement
Après, j'ai pas mis les mains autant dedans que toi, si tu le sens, je te fais confiance et on y va comme ça mais il faut bien avoir en tête que c'est ce qui répond de façon automatique aux éditeurs qui essaient de se raccorder !

2024-03-01 20:02 UTC, romainfd approved these changes
Je vais merger pour qu'on puisse passer à autre chose et parce que les messages sont très clairs d'un point de vue éditeur mais je crée une tâche Asana pour refactoriser le code de génération des messages d'erreur

2024-03-01 20:02 UTC, merged