feat/Ajout de wrapper pour les messages RS-INFO
ansforge/SAMU-Hub-Modeles pull request #29
Opened 2024-01-18 12:34 UTC by saveliy-sviridov

2024-01-18 15:57 UTC, saveliy-sviridov commented
A revérifier que les "additionalProperties:false" sont proprement positionnés

2024-01-22 08:54 UTC, romainfd approved these changes
Quelques petits commentaires pour en rediscuter mais ça me semble très bien !
Je laisse @bou3108 regarder plus en détails la partie Modèle

2024-01-22 08:54 UTC, romainfd commented on src/main/java/com/hubsante/model/builders/InfoWrapperBuilder.java
> +}
Sans le RC-DE, je sais pas si le wrapper a beaucoup de sens

2024-01-22 08:54 UTC, romainfd commented on src/main/java/com/hubsante/model/report/InfoWrapper.java
Je laisse Benjamin s'exprimer sur les annotations & co, il est plus familier que moi !

2024-01-22 08:54 UTC, romainfd commented on src/main/resources/json-schema/RS-INFO.schema.json
> +        "sourceMessage",
Est-ce qu'on le mettrait pas en facultatif plutôt ? Comme ça, à terme, on pourra directement l'enlever sans rien casser normalement. Avec referencedDistributionId, il y a déjà de quoi retrouver le message, le but de le fournir est juste de simplifier le debug

2024-01-22 08:54 UTC, romainfd commented on src/main/resources/json-schema/RS-INFO.schema.json
> +        "sourceMessage",
Du coup, il faudrait aussi le modifier dans ErrorReport je pense
Et, au passage, possible de modifier l'ordre pour que le sourceMessage soit en dernier ? Parce que c'est en général un gros blob et du coup, il prend bcp de place.
Pour en faciliter l'exploitation, est-ce qu'on pourrait lui donner un type JSON / Objet / ... ou autre un peu comme CustomContent d'ailleurs ? Comme ça on peut passer les infos de façon structurée plutôt qu'en string qui est galère à lire dans les messages reçus

2024-01-22 08:54 UTC, romainfd commented on src/main/resources/sample/failing/RS-INFO/RS-INFO-missing-required-fields.json
>              "sourceMessage": "source"
Indenter ?

2024-01-22 14:18 UTC, bou3108 requested changes
Je recommanderais l'ajout de deux TUs pour valider le comportement sur la spec "additionalProperties = false", avec les quelques modifications mineures suggérées par Romain

2024-01-22 14:18 UTC, bou3108 commented on src/main/resources/json-schema/RS-INFO.schema.json
> +        "sourceMessage",
Rendre facultatif le sourceMessage ? Je ne suis pas sûr de bien identifier la ligne sur laquelle tu fais ce commentaire. Si oui, parfaitement aligné.

2024-01-22 14:18 UTC, bou3108 commented on src/main/resources/json-schema/RS-INFO.schema.json
> +        "sourceMessage",
Et typer le sourceMessage en Object (plus souple que JsonNode pour nous) permettra bien de structurer correctement l'output

2024-01-22 14:18 UTC, bou3108 commented on src/main/resources/json-schema/RS-INFO.schema.json
> +        "sourceMessage",
Aligné aussi sur la modification de l'annotation @JsonPropertyOrder dans la classe ErrorReport.

2024-01-22 14:18 UTC, bou3108 commented on src/main/resources/json-schema/EDXL-DE-full.schema.json
>          },
Je pense que l'ajout de cette mention est sans effet.
Deux tests unitaires seraient utiles d'ailleurs sur le sujet : 
- un premier avec un champ additionnel inconnu à la racine du wrapper (au même niveau que les champs du RC-DE ou le createCase)
- un second avec un champ additionnel inconnu à la racine (ou plus bas) d'un objet "métier" (createCase, emsi, etc).

Le second test échouera, le premier sera passant. L'ajout de la mention "additionalProperties" à l'intérieur du allOf ne change rien à l'affaire.

Nous en avions discuté rapidement avec Romain et je ne vois pas comment modifier ce comportement, je crois que c'est un cornercase lié à notre double utilisation allOf + recours à sub schema.

Dans ce cas très spécifique (propriété additionnelle dans l'un des wrapper uniquement, et aucune autre erreur ailleurs dans le schema), la validation passera et la désérialisation échouera.
C'est ce que devrait tester le 1er TU d'ailleurs.

2024-01-26 12:32 UTC, romainfd requested changes
Quelques petits updates suite à nos échanges de mercredi à faire je pense

2024-01-26 12:32 UTC, romainfd commented on src/main/java/com/hubsante/model/report/ErrorReport.java
> +    public ErrorReport(ErrorCode errorCode, String errorCause, Object sourceMessage, String referencedDistributionID) {
Du coup, quelle est la différence entre Object et JSON Node ? Il faudrait uniformiser entre les deux (avec Custom Content) pour ne garder que le même partout

2024-01-26 12:32 UTC, romainfd commented on src/test/java/com/hubsante/model/EdxlHandlerTest.java
> +        assertDoesNotThrow(() -> converter.deserializeJsonEDXL(json));
Pourquoi ça ne fail pas ??  Il faudrait que ça casse en effet et ne pas avoir d'ignore unknown sur ça ! On ne l'avait pas supprimé pendant notre point mercredi justement ?
Après, la validation bloquera déjà ça normalement mais quand même

2024-01-26 12:32 UTC, romainfd commented on src/test/java/com/hubsante/model/ValidatorTest.java
> +        assertDoesNotThrow(() -> validator.validateJSON(json, FULL_SCHEMA));
Que veut dire "RC-DE validation" ?
Oui il faudrait que ça plante justement ! On a dit qu'on enlevait le AllOf à la racine de l'EDXL full en incluant directement en dur l'EDXL DE non ?

2024-02-13 14:54 UTC, merged