Feat/Reprise des objets nomenclatures
ansforge/SAMU-Hub-Modeles pull request #35
Opened 2024-02-07 14:46 UTC by saveliy-sviridov

Ajout de définition par objet de type nomenclature dans les schémas générés.

2024-02-13 16:36 UTC, romainfd requested changes
Simplifier la logique du csv_parser, supprimer la colonne inutile du MDD excel, reprendre le type pour coller avec le MDD (codeLabelComment) et le surcharger pour nous par le nom la balise avec la 1ère lettre en majuscule (HealthMotive, LocationKind, ...)

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +            return child
Le problème avec ça est que les lignes sont ajoutées bien trop tard et qu'elles ont donc une logique complètement particulière qui ne colle plus avec le reste !
Leur level n'augmente plus alors que normalement il doit augmenter de 1 dans au moins une colonne pour chaque saut de ligne
POur les nomenclatures
<img width="581" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/aea55ccf-644a-470d-b0e3-9b0fac9705e0">

Attendu 
<img width="508" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/21e91c15-ff16-4816-9c8a-0e56e3c16d17">

A priori, c'est pas cassant pour le moment mais avoir des spécificités comme ça dans le df peut nous compliquer la vie dans le futur je pense parce que ça casse tous les invariants / logiques du truc.

Ca ne serait pas possible de l'intégrer plutôt à la ligne ~128 ?

Si le problème, c'est de savoir à quel niveau (quel colonne), il faut l'insérer, je pense que juste trouver à quel n° de colonne "Donnée ..." est écrit le nom (= chercher le 1er non NaN) et rajouter 1 devrait être OK
<img width="863" alt="image" src="https://github.com/ansforge/SAMU-Hub-Modeles/assets/32517197/533734e7-01dd-42e5-a99c-1a8e4b72ac36">

2024-02-13 16:36 UTC, romainfd commented on csv_parser/json_schema2xsd/src/main/resources/RC-EDA.schema.json
> +                    "$ref": "#/definitions/nomenclatureWhatsHappen"
Comme vu ce matin, pas nécessaire finalement !

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
On voit dans REQUIRED_COLUMNS qu'on peut virer la colonne "Nomenclature / Enum" de l'excel du coup

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +    df.sort_index(axis=0, ascending=True, inplace=True, kind='quicksort')
Si tu gardes ça, fais un reset_index(drop=True) ensuite pour repartir sur des indices entiers et cleans

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +            return 'nomenclature'+capitalizeFirstLetter(row['name'])
Plus nécessaire du coup non ?

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +        childType = child['Format (ou type)']
Pourquoi ce changement ?

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +        childType = child['Format (ou type)']
On avait un doublon entre childTypeName et typeName ?!

2024-02-13 16:36 UTC, romainfd commented on csv_parser/csv_parser.py
> +        childType = child['Format (ou type)']
plutôt garder childTypeName qui est plus clair que typeName pour child['true_type']

2024-02-14 09:50 UTC, saveliy-sviridov commented on csv_parser/csv_parser.py
> +        childType = child['Format (ou type)']
Pour les nomenclatures spécifiquement il nous faut à la fois le type "originel" et le "true_type", j'ai renommé les variables en childOriginalTypeName et childTrueTypeName

2024-03-01 21:08 UTC, romainfd approved these changes
LGTM, thanks!

2024-03-01 21:27 UTC, merged