Feat/Validation de distributionId dans builder
ansforge/SAMU-Hub-Modeles pull request #47
Opened 2024-02-21 13:10 UTC by saveliy-sviridov

Ajout d'une simple vérification de structure et cohérence entre distributionId et senderId dans le builder dans EDXL_DE_Builder

2024-02-27 11:01 UTC, romainfd requested changes
Quelques petits retours mais top !

2024-02-27 11:01 UTC, romainfd commented on src/main/java/com/hubsante/model/builders/EDXL_DE_Builder.java
> +        }
Un éditeur qui envoie un message pas bien formatté, il va recevoir un message error avec cette info du coup ?

2024-03-04 15:51 UTC, saveliy-sviridov commented on src/main/resources/json-schema/EDXL-DE-envelope-only.schema.json
> +          "pattern": "^([a-z]|[0-9]|\\.|_|\\-|#)+_([a-z]|[0-9]|\\.|_|\\-|#)+$"
Ca ne parait pas fonctionner sans le double slash:
![image](https://github.com/ansforge/SAMU-Hub-Modeles/assets/105354733/e3c19ab8-9d86-4bab-bc9d-d1187b0e3d2e)

2024-03-04 16:00 UTC, saveliy-sviridov commented on src/main/java/com/hubsante/model/builders/EDXL_DE_Builder.java
> +        }
Ces messages d'erreur sont specifiquement pour le builder, dans le cas d'envoi d'un message erroné l'editeur va recevoir soit un InvalidDistributionIDException dans le cas de senderId non conforme, soit SchemaValidationException si distributionId ne passe pas la validation regex

2024-03-05 13:31 UTC, bou3108 commented on src/test/java/com/hubsante/model/builders/ReferenceWrapperBuilderTest.java
> +        ReferenceWrapper referenceWrapper = new ReferenceWrapperBuilder(distributionElement, "test.sender-x_ID12345")
Pourquoi ne pas utiliser la constante que tu as définie plus haut ?

2024-03-05 13:33 UTC, bou3108 commented on src/test/java/com/hubsante/model/builders/CreateCaseWrapperBuilderTest.java
>      private EdxlHandler converter = new EdxlHandler();
Pourquoi ne pas créer un fichier de constantes dans le package test ? Pour ne pas dupliquer ces définitions

2024-03-05 13:34 UTC, bou3108 commented on src/test/java/com/hubsante/model/builders/ReferenceWrapperBuilderTest.java
Pourquoi ne pas utiliser la constante plus tôt ?

2024-03-05 13:35 UTC, bou3108 approved these changes
LGTM

Pour plus de maintenabilité, on devrait pouvoir définir les constantes utilisées dans les tests de façon centralisée

2024-03-05 14:58 UTC, bou3108 approved these changes

2024-03-05 14:59 UTC, merged