Feat/Migration de RC-REF, RS-ERROR, RS-INFO et CustomContent vers l'excel mdd
ansforge/SAMU-Hub-Modeles pull request #50
Opened 2024-02-28 13:44 UTC by saveliy-sviridov

Ajout de feuilles RC-REF, RS-ERROR, RS-INFO et CustomContent dans model.xslx et modifications de parser liées.

2024-04-04 15:39 UTC, romainfd reviewed
Ca me semble pas mal mais je suis pas trop expert sur ce périmètre et je pense qu'il faut que Benjamin y jette un oeil également !

2024-04-04 15:39 UTC, romainfd commented on src/main/resources/xsd/RC-REF.xsd
> +            <element minOccurs="0" name="refused" type="boolean">
Benjamin, ça avait pas été hot-fixé ça ?

2024-04-04 15:39 UTC, romainfd commented on .github/workflows/generate-model.yaml
> +  SCHEMAS: "RC-EDA RS-EDA EMSI GEO-POS GEO-REQ GEO-RES RC-REF RS-ERROR"
Pas CustomContent et Info du coup ?

2024-04-05 07:14 UTC, romainfd commented on src/main/resources/xsd/RC-REF.xsd
> +            <element minOccurs="0" name="refused" type="boolean">
https://github.com/ansforge/SAMU-Hub-Modeles/pull/66/files#diff-fc38693f8ccd642d2c6cead34eed2b1946cf12652356ef6438b12bc61f21c864 pas mergé dans develop aussi ?

2024-04-05 07:18 UTC, romainfd commented
Renommer infoDistributionId dans RC-REF à errorDistributionId

2024-04-08 08:15 UTC, romainfd reviewed
LGTM! Je laisse @bou3108 jeter un oeil expert !

2024-04-08 13:32 UTC, bou3108 commented on src/main/resources/xsd/RC-REF.xsd
> +            <element minOccurs="0" name="refused" type="boolean">
Le hotfix sur common.openapi.yaml avait été porté mais pas le xsd
Je m'attendais à ce qu'il soit regénéré automatiquement par la github action (json2xsd) mais je pense que le filtre l'a bloqué
je l'ai porté manuellement

2024-04-08 13:40 UTC, bou3108 commented on .github/workflows/generate-model.yaml
> +  SCHEMAS: "RC-EDA RS-EDA EMSI GEO-POS GEO-REQ GEO-RES RC-REF RS-ERROR"
CustomContent, ça peut être compliqué / pas très utile : le générateur va déduire du champ properties: {} que c'est une HashMap, quand on a souhaité avoir un JsonNode pour faciliter la génération des messages d'erreur.

Par contre effectivement RS-INFO y aurait sa place, dès l'instant ou le parser génère json schema & spec openapi

2024-04-08 13:50 UTC, bou3108 requested changes
Il faudrait également modifier common.openapi.yaml, sans quoi nous allons continuer à générer Reference et referenceWrapper en doublon; de plus les imports dans les builders pointent encore vers les anciens

Si seul les éléments du RC-DE finissent par rester dans le common.openapi.yaml (DistributionElement, Sender, Recipient), il sera sans doute pertinent de renommer et ce fichier, et le package Java.

Supprimer aussi le package report, s'il est remplacé par error => cela aura également un impact sut les builders, et sur les appels dans le Dispatcher (méthode logErrorAndSendReport + TUs)

2024-04-09 12:58 UTC, bou3108 requested changes

2024-04-09 12:58 UTC, bou3108 commented on .github/workflows/generate-model.yaml
> +  SCHEMAS: "RC-EDA RS-EDA EMSI GEO-POS GEO-REQ GEO-RES RC-REF RS-ERROR"
Du coup @saveliy-sviridov  on n'intègre pas RS-INFO ?

2024-04-09 12:58 UTC, bou3108 commented on src/main/java/com/hubsante/model/edxl/ContentMessage.java
Import non utilisé non ?

2024-04-09 12:58 UTC, bou3108 commented on src/main/java/com/hubsante/model/error/ErrorWrapper.java
> +  String xmlns = "urn:emergency:cisu:2.0";
le template ne fonctionne pas

-> className plutôt que class non ?

2024-04-09 12:58 UTC, bou3108 commented on src/main/java/com/hubsante/model/error/ErrorWrapper.java
> +import com.hubsante.edxl.;
le template ne fonctionne pas

2024-04-09 13:30 UTC, saveliy-sviridov commented
Pour le moment on n'intègre pas RS-INFO puisqu'il a été remplacé fonctionnellement par RS-ERROR et n'est plus utilisé.

2024-04-24 14:45 UTC, merged