WIP: Feature/Ajout de parseur pour la génération de cas de test
ansforge/SAMU-Hub-Modeles pull request #52
Opened 2024-03-05 13:18 UTC by saveliy-sviridov

Ajout d'un deuxième parseur csv permettant de générer test-cases.json à utiliser par l'interface de test.

2024-04-08 13:38 UTC, romainfd requested changes
C'est une bonne première base mais je pense qu'il faut encore un peu creuser le besoin fonctionnel (et plus tard aussi le "hardening" du script)
En attendant, déjà quelques petits commentaires / retours à prendre en compte avant de merge (et de créer les tâches Asana pour les autres sujets) notamment sur le split dans workflow.py

2024-04-08 13:38 UTC, romainfd commented on csv_parser/test_case_generator.py
> +                            if pd.notna(row[i]):
Ca veut dire qu'on ne peut pas ajouter / supprimer des colonnes sans reprendre le parser
Pourquoi ne pas accéder aux colonnes avec `f"JDD {i+1} for i in range(5)` ? Cela privilégie les accès par le nom de colonne, plus simple à maintenir dans le temps

2024-04-08 13:38 UTC, romainfd commented on csv_parser/test_case_generator.py
> +                        "label": row["Pas de test"] + " " + row["Unnamed: 1"],
C'est parce que les colonnes A et B sont sous le même header ?
Dans ce cas, plutôt mettre 2 headers "Direction" et "Modèle" dans l'excel et avoir une logique plus claire ici non ?

2024-04-08 13:38 UTC, romainfd commented on csv_parser/test_case_generator.py
> +                        "description": row["Déroulé métier"],
Quid de la colonne "Description" justement ?

2024-04-08 13:38 UTC, romainfd commented on csv_parser/test_case_generator.py
> +        return "receive"
Là comme à d'autres endroits, je pense que ça serait intéressant de gérer les cas d'erreur ou de mauvais formatage
Pour le moment, on peut rester comme ça mais je pense qu'il faudra une phase de hardening quand on aura du gérer plusieurs erreurs sur le workflow

2024-04-08 13:38 UTC, romainfd commented on src/main/resources/test-cases.json
Tu as pu testé de le charger dans le LRM ? Ca donnait bien ce qu'on voulait ?

2024-04-08 13:38 UTC, romainfd commented on src/main/resources/test-cases.json
> +                                    "$.createCaseHealth.qualification.whatsHappen.code",
Par exemple, je suis surpris que cette valeur soit ici -> aussi un autre intérêt de l'accès par nom et pas par indice de la colonne, c'est que c'est plus clair sur les colonnes prises

2024-04-10 08:45 UTC, saveliy-sviridov commented on src/main/resources/test-cases.json
J'ai corrigé un petit problème (wrappeur message manquant) et le resultat me parait correcte:
![image](https://github.com/ansforge/SAMU-Hub-Modeles/assets/105354733/cb3a2003-bd5e-4875-8ecf-5053b108f710)

2024-04-11 16:39 UTC, romainfd approved these changes
Très bien, merci beaucoup pour les reprises !

2024-04-11 16:40 UTC, merged